### PR TITLE
Travis Config

### PR DESCRIPTION
**Pull request by anantjain6**
Demo of this config can be found at https://travis-ci.org/anantjain6/collaborative_editors/builds/552157283

### CODE REVIEW

**Review by ankitjain28may — CHANGES_REQUESTED** [review]
It only contains coding standard check, what about PHPUnit tests?

**Comment by anantjain6** [comment]
Add PHP Unit Testing with commit 9f42032
Demo of config https://travis-ci.org/anantjain6/collaborative_editors/builds/552488254

**Review by ankitjain28may — CHANGES_REQUESTED** [review]
Awesome, But the Travis is still failing because of code-sniffer errors, check it and also use `phpcbf`

**Comment by anantjain6** [comment]
Could you please merge this PR
Then I'll raise a new PR with codes of #6 which are passing all the tests

**Comment by ankitjain28may** [comment]
Can't we fix the code-sniffer errors within this PR?

**Comment by anantjain6** [comment]
All Travis tests passed with 720c9eb

**Review by ankitjain28may — APPROVED** [review]
Nice :)

**Pull request merged**
